/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CodesRouteImport } from './routes/codes'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as ClassesIndexRouteImport } from './routes/classes.index'
import { Route as ClassesSessionIdRouteImport } from './routes/classes.$sessionId'
import { Route as StudentsIndexRouteImport } from './routes/students.index'
import { Route as StudentsStudentIdRouteImport } from './routes/students.$studentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CodesRoute = CodesRouteImport.update({
  id: '/codes',
  path: '/codes',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesIndexRoute = ClassesIndexRouteImport.update({
  id: '/classes/',
  path: '/classes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesSessionIdRoute = ClassesSessionIdRouteImport.update({
  id: '/classes/$sessionId',
  path: '/classes/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIndexRoute = StudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsStudentIdRoute = StudentsStudentIdRouteImport.update({
  id: '/students/$studentId',
  path: '/students/$studentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/codes': typeof CodesRoute
  '/payments': typeof PaymentsRoute
  '/classes/$sessionId': typeof ClassesSessionIdRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/classes/': typeof ClassesIndexRoute
  '/students/': typeof StudentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/codes': typeof CodesRoute
  '/payments': typeof PaymentsRoute
  '/classes/$sessionId': typeof ClassesSessionIdRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/classes': typeof ClassesIndexRoute
  '/students': typeof StudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/codes': typeof CodesRoute
  '/payments': typeof PaymentsRoute
  '/classes/$sessionId': typeof ClassesSessionIdRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/classes/': typeof ClassesIndexRoute
  '/students/': typeof StudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/codes'
    | '/payments'
    | '/classes/$sessionId'
    | '/students/$studentId'
    | '/classes/'
    | '/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/codes'
    | '/payments'
    | '/classes/$sessionId'
    | '/students/$studentId'
    | '/classes'
    | '/students'
  id:
    | '__root__'
    | '/'
    | '/codes'
    | '/payments'
    | '/classes/$sessionId'
    | '/students/$studentId'
    | '/classes/'
    | '/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CodesRoute: typeof CodesRoute
  PaymentsRoute: typeof PaymentsRoute
  ClassesSessionIdRoute: typeof ClassesSessionIdRoute
  StudentsStudentIdRoute: typeof StudentsStudentIdRoute
  ClassesIndexRoute: typeof ClassesIndexRoute
  StudentsIndexRoute: typeof StudentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codes': {
      id: '/codes'
      path: '/codes'
      fullPath: '/codes'
      preLoaderRoute: typeof CodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/': {
      id: '/classes/'
      path: '/classes'
      fullPath: '/classes/'
      preLoaderRoute: typeof ClassesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/$sessionId': {
      id: '/classes/$sessionId'
      path: '/classes/$sessionId'
      fullPath: '/classes/$sessionId'
      preLoaderRoute: typeof ClassesSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/': {
      id: '/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof StudentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$studentId': {
      id: '/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof StudentsStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodesRoute: CodesRoute,
  PaymentsRoute: PaymentsRoute,
  ClassesSessionIdRoute: ClassesSessionIdRoute,
  StudentsStudentIdRoute: StudentsStudentIdRoute,
  ClassesIndexRoute: ClassesIndexRoute,
  StudentsIndexRoute: StudentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
